# Generated by Django 5.0.4 on 2024-06-16 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('usuario', models.CharField(max_length=50)),
                ('tipo_proceso', models.CharField(max_length=50)),
                ('variedad_cafe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maquina', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=8)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Proceso',
                'verbose_name_plural': 'Tipos de Procesos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=20)),
                ('nombres_completos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 10 dígitos', regex='^\\d{10}$')])),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=8)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Operario', 'Operario'), ('Proveedor', 'Proveedor')], max_length=20)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Variedad',
                'verbose_name_plural': 'Variedades',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Operando', 'Operando'), ('Fuera de Servicio', 'Fuera de Servicio'), ('En Mantenimiento', 'En Mantenimiento')], max_length=18)),
                ('lote_cafe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.lotecafe')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.maquina')),
                ('id_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.tipoproceso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
            },
        ),
    ]
