# Generated by Django 5.0.4 on 2024-06-17 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotecafe',
            options={'verbose_name': 'LoteCafe', 'verbose_name_plural': 'LotesCafe'},
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('temperatura_s1', models.FloatField()),
                ('temperatura_s2', models.FloatField()),
                ('temperatura_promedio', models.FloatField()),
                ('fecha', models.DateField()),
                ('id_maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.maquina')),
            ],
            options={
                'verbose_name': 'Dato',
                'verbose_name_plural': 'Datos',
            },
        ),
    ]
