# Generated by Django 4.2.13 on 2024-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
