# Generated by Django 4.2.13 on 2024-05-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appProyecto', '0002_alter_maquina_id_alter_seguimiento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='lote_cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.lotecafe'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.maquina'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='operario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appProyecto.operario'),
        ),
    ]
